@startuml

actor User
participant ":Parser" as Parser
participant ":UiAssistFactory" as Assist
participant ":TransactionsList" as List

User -> Parser : add

alt UI Assist ON
    Parser -> Assist : getInteractiveArguments()
    Assist --> Parser : generated command
end

Parser -> List : addTransaction(...)
List --> User : success

@enduml
