@startuml
skinparam backgroundColor #EEEBDC
skinparam sequence {
    ParticipantBackgroundColor #FFF
    ActorBackgroundColor #FFF
    LifeLineBackgroundColor #FFF
}
actor User
participant ":Parser" as Parser
participant ":TransactionsList" as TransactionsList
participant "t:Transaction" as Transaction

User -> Parser : processInput("edit 1 -a 100")
activate Parser

Parser -> TransactionsList : editTransaction(1, null, null, 100.0, null, null)
activate TransactionsList

TransactionsList -> TransactionsList : findById(1)
activate TransactionsList
TransactionsList --> TransactionsList : t
deactivate TransactionsList

TransactionsList -> Transaction : update(null, null, 100.0, null, null)
activate Transaction
Transaction --> TransactionsList
deactivate Transaction

TransactionsList --> Parser
deactivate TransactionsList

Parser --> User : "Transaction edited successfully."
deactivate Parser
@enduml
